import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

export const translations = {
  en: {
    brand: 'Balaji Communication & Services',
    brandShort: 'Balaji Communication',
    tagline: '& Services',
    nav_services: 'Services',
    nav_contact: 'Contact',
    nav_call: 'Call Now',
    hero_badge: 'Trusted Local Services',
    hero_title: 'Balaji Communication',
    hero_grad: '& Services',
    hero_sub: 'All Services Under One Roof',
    hero_desc: 'Fast, hassle-free services with personal support for every customer.',
    hero_cta1: 'Explore Services',
    hero_cta2: '📞 9848651632',
    services_label: 'What We Offer',
    services_title: 'Our Services',
    services_sub: 'Click any service to see full details',
    why_label: 'Our Promise',
    why_title: 'Why Customers Trust Us',
    trust1_title: 'Time-Saving',
    trust1_desc: "We handle paperwork quickly so you don't wait.",
    trust2_title: 'Transparent Pricing',
    trust2_desc: 'Clear pricing with no hidden charges.',
    trust3_title: 'Personal Support',
    trust3_desc: 'Dedicated assistance for every customer.',
    trust4_title: 'Local Expertise',
    trust4_desc: 'Strong understanding of local processes and requirements.',
    contact_label: 'Get In Touch',
    contact_title: 'Contact Us',
    contact_desc: "We're here to help you with all your service needs. Reach out anytime.",
    phone_label: 'Phone',
    hours_label: 'Working Hours',
    hours_val: 'Mon – Sat: 9:00 AM – 7:00 PM',
    loc_label: 'Location',
    loc_val: 'Kaverammapeta Chourasta, Jadcherla, Mahabubnagar Dist – 509301, Telangana',
    call_btn: 'Call Now: 9848651632',
    footer_copy: '© 2025 Balaji Communication & Services. All rights reserved.',
    lang_toggle: 'తెలుగు',
  },
  te: {
    brand: 'బాలాజీ కమ్యూనికేషన్ & సేవలు',
    brandShort: 'బాలాజీ కమ్యూనికేషన్',
    tagline: '& సేవలు',
    nav_services: 'సేవలు',
    nav_contact: 'సంప్రదించండి',
    nav_call: 'కాల్ చేయండి',
    hero_badge: 'విశ్వసనీయ స్థానిక సేవలు',
    hero_title: 'బాలాజీ కమ్యూనికేషన్',
    hero_grad: '& సేవలు',
    hero_sub: 'అన్ని సేవలు ఒకే చోట',
    hero_desc: 'ప్రతి కస్టమర్‌కు వ్యక్తిగత మద్దతుతో వేగవంతమైన, ఇబ్బంది లేని సేవలు.',
    hero_cta1: 'సేవలు చూడండి',
    hero_cta2: '📞 9848651632',
    services_label: 'మేము అందించేది',
    services_title: 'మా సేవలు',
    services_sub: 'పూర్తి వివరాల కోసం ఏదైనా సేవను క్లిక్ చేయండి',
    why_label: 'మా వాగ్దానం',
    why_title: 'కస్టమర్లు మాపై విశ్వాసం ఉంచే కారణం',
    trust1_title: 'సమయం ఆదా',
    trust1_desc: 'మీరు వేచి ఉండకుండా మేము పేపర్‌వర్క్ వేగంగా నిర్వహిస్తాము.',
    trust2_title: 'పారదర్శక ధర',
    trust2_desc: 'దాచిన చార్జీలు లేకుండా స్పష్టమైన ధర.',
    trust3_title: 'వ్యక్తిగత మద్దతు',
    trust3_desc: 'ప్రతి కస్టమర్‌కు అంకితమైన సహాయం.',
    trust4_title: 'స్థానిక నైపుణ్యం',
    trust4_desc: 'స్థానిక ప్రక్రియలు మరియు అవసరాల గురించి బలమైన అవగాహన.',
    contact_label: 'సంప్రదించండి',
    contact_title: 'మమ్మల్ని సంప్రదించండి',
    contact_desc: 'మేము మీ అన్ని సేవా అవసరాలలో సహాయం చేయడానికి ఇక్కడ ఉన్నాము.',
    phone_label: 'ఫోన్',
    hours_label: 'పని గంటలు',
    hours_val: 'సోమ – శని: ఉ. 9:00 – సా. 7:00',
    loc_label: 'స్థానం',
    loc_val: 'కావేరమ్మపేట చౌరస్తా, జడ్చర్ల, మహబూబ్ నగర్ జిల్లా – 509301, తెలంగాణ',
    call_btn: 'ఇప్పుడు కాల్ చేయండి: 9848651632',
    footer_copy: '© 2025 బాలాజీ కమ్యూనికేషన్ & సేవలు. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    lang_toggle: 'English',

    'Internet & MeeSeva Services': 'ఇంటర్నెట్ & మీసేవ సేవలు',
    'One-stop solution for government services, internet access, and digital applications.': 'ప్రభుత్వ సేవలు, ఇంటర్నెట్ యాక్సెస్ మరియు డిజిటల్ అప్లికేషన్‌ల కోసం ఒకే చోట పరిష్కారం.',
    'Real Estate & Construction': 'రియల్ ఎస్టేట్ & నిర్మాణం',
    'Complete support for property-related services and construction activities.': 'ఆస్తి సంబంధిత సేవలు మరియు నిర్మాణ కార్యకలాపాలకు పూర్తి మద్దతు.',
    'Business Consultancy': 'వ్యాపార కన్సల్టెన్సీ',
    'Professional support for personal, local, and business-related services.': 'వ్యక్తిగత, స్థానిక మరియు వ్యాపార సంబంధిత సేవలకు వృత్తిపరమైన మద్దతు.',
    'Financial & Tax Support': 'ఆ ఆర్థిక & పన్ను మద్దతు',
    'Support for financial planning and tax-related services for individuals and businesses.': 'వ్యక్తులు మరియు వ్యాపారాల కోసం ఆర్థిక ప్రణాళిక మరియు పన్ను సంబంధిత సేవలకు మద్దతు.',
    
    'Birth Certificate': 'జనన ధృవీకరణ పత్రం',
    'Death Certificate': 'మరణ ధృవీకరణ పత్రం',
    'Caste Certificate': 'కుల ధృవీకరణ పత్రం',
    'Income Certificate': 'ఆదాయ ధృవీకరణ పత్రం',
    'Residence Certificate': 'నివాస ధృవీకరణ పత్రం',
    'Adangal (Land Records)': 'అడంగల్ (భూమి రికార్డులు)',
    'Utility Bill Payments': 'యుటిలిటీ బిల్ చెల్లింపులు',
    'Online Job Applications': 'ఆన్‌లైన్ ఉద్యోగ దరఖాస్తులు',
    'Scanning & Printing': 'స్కానింగ్ & ప్రింటింగ్',
    'Exam Results & Hall Tickets': 'పరీక్షా ఫలితాలు & హాల్ టిక్కెట్లు',
    'Passport Application Support': 'పాస్‌పోర్ట్ దరఖాస్తు మద్దతు',
    'PAN Card Application Support': 'పాన్ కార్డ్ దరఖాస్తు మద్దతు',
    'Property Buying Support': 'ఆస్తి కొనుగోలు మద్దతు',
    'Property Selling Support': 'ఆస్తి విక్రయ మద్దతు',
    'Rental Assistance': 'అద్దె సహాయం',
    'House/Shop Leasing Support': 'ఇల్లు/దుకాణం లీజింగ్ మద్దతు',
    'Construction Coordination': 'నిర్మాణ సమన్వయం',
    'Plot Verification': 'ప్లాట్ ధృవీకరణ',
    'Legal Documentation Support': 'చట్టపరమైన పత్రాల మద్దతు',
    'Registration Guidance': 'రిజిస్ట్రేషన్ మార్గదర్శకత్వం',
    'Property Consultation': 'ఆస్తి సంప్రదింపులు',
    'Site Visit Coordination': 'సైట్ సందర్శన సమన్వయం',
    'Business Registration': 'వ్యాపార నమోదు',
    'Shop Registration': 'దుకాణ నమోదు',
    'GST Registration Guidance': 'GST నమోదు మార్గదర్శకత్వం',
    'Documentation & Approvals': 'పత్రాలు & ఆమోదాలు',
    'Service Coordination': 'సేవల సమన్వయం',
    'Government Application Support': 'ప్రభుత్వ దరఖాస్తు మద్దతు',
    'Local Business Setup Guidance': 'స్థానిక వ్యాపార ఏర్పాటు మార్గదర్శకత్వం',
    'Follow-ups & Assistance': 'ఫాలో అప్‌లు & సహాయం',
    'Office Documentation Help': 'కార్యాలయ పత్రాల సహాయం',
    'PAN Card Services': 'పాన్ కార్డ్ సేవలు',
    'Income Tax Return (ITR Filing)': 'ఆదాయపు పన్ను రిటర్న్ (ITR ఫైలింగ్)',
    'Investment Documentation': 'పెట్టుబడి పత్రాలు',
    'Basic Financial Planning': 'ప్రాథమిక ఆర్థిక ప్రణాళిక',
    'Tax Filing Support': 'పన్ను ఫైలింగ్ మద్దతు',
    'Financial Consultation': 'ఆర్థిక సంప్రదింపులు',
    'Small Business Tax Guidance': 'చిన్న వ్యాపార పన్ను మార్గదర్శకత్వం',
    'Account Documentation Support': 'ఖాతా పత్రాల మద్దతు',

    '🌐 Internet & MeeSeva': '🌐 ఇంటర్నెట్ & మీసేవ',
    '🏠 Real Estate & Construction': '🏠 రియల్ ఎస్టేట్ & నిర్మాణం',
    '💼 Business Consultancy': '💼 వ్యాపార కన్సల్టెన్సీ',
    '💰 Financial & Tax Support': '💰 ఆర్థిక & పన్ను మద్దతు',

    'Founder & Proprietor': 'వ్యవస్థాపకుడు & యజమాని',
    'Potti Srinivasulu': 'పొట్టి శ్రీనివాసులు',
    'With 15+ years of trusted experience serving customers through internet services, MeeSeva, real estate, consultancy, and business support.': 'ఇంటర్నెట్ సేవలు, మీసేవ, రియల్ ఎస్టేట్, కన్సల్టెన్సీ మరియు వ్యాపార మద్దతు ద్వారా కస్టమర్లకు సేవలందించడంలో 15+ సంవత్సరాల విశ్వసనీయ అనుభవంతో.',
    'Talk to an Expert →': 'నిపుణుడితో మాట్లాడండి →',

    'contact_call_title': 'కాల్ చేయండి',
    'contact_call_text': 'నేరుగా పొట్టి శ్రీనివాసులుతో మాట్లాడండి',
    'contact_email_title': 'ఈమెయిల్ పంపండి',
    'contact_email_text': 'మీ పత్రాలు లేదా సందేహాలను పంపండి',
    'contact_visit_title': 'మమ్మల్ని సందర్శించండి',
    'contact_form_title': 'మాకు సందేశం పంపండి',
    'contact_form_fname': 'మొదటి పేరు',
    'contact_form_fname_ph': 'మీ మొదటి పేరు నమోదు చేయండి',
    'contact_form_email': 'ఈమెయిల్ చిరునామా',
    'contact_form_email_ph': 'మీ ఈమెయిల్ నమోదు చేయండి',
    'contact_form_subject': 'విషయం',
    'contact_form_subject_ph': 'ఇది దేని గురించి?',
    'contact_form_msg': 'సందేశం',
    'contact_form_msg_ph': 'మీ సందేశాన్ని ఇక్కడ రాయండి...',
    'contact_form_submit': 'సందేశం పంపండి'
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('bcs-lang') || 'en')
  const toggle = () => {
    const next = lang === 'en' ? 'te' : 'en'
    setLang(next)
    localStorage.setItem('bcs-lang', next)
  }
  const t = (key, defaultText) => translations[lang]?.[key] || defaultText || key
  return <LangContext.Provider value={{ lang, toggle, t }}>{children}</LangContext.Provider>
}

export const useLang = () => useContext(LangContext)
